'use client';

import { useState, useRef, useEffect } from 'react';

export default function ExportRoadmapButton({ 
  repoUrl, 
  issueNumber, 
  explainData, 
  planData, 
  testsData, 
  prData,
  onShowToast 
}) {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef(null);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const generateMarkdownContent = () => {
    const issueTitle = explainData?.issue?.title || `Issue #${issueNumber}`;
    const timestamp = new Date().toUTCString();
    
    let md = `# 🗺️ Hacktoberfest Contribution Roadmap\n\n`;
    md += `**Repository:** [${repoUrl}](${repoUrl})\n`;
    md += `**Issue:** #${issueNumber} — ${issueTitle}\n`;
    md += `**Difficulty:** ${explainData?.difficulty || 'Beginner'}\n`;
    md += `**Generated On:** ${timestamp}\n`;
    md += `**Generated By:** [Hacktoberfest Copilot](https://github.com/AsmitAnand/HacktoberFest-Team-GrandCoders)\n\n`;
    md += `---\n\n`;

    // 1. Understand
    md += `## 🧠 1. Understand the Problem\n\n`;
    md += `### Simplified Breakdown\n${explainData?.simplified_explanation || 'N/A'}\n\n`;
    
    if (explainData?.required_skills?.length > 0) {
      md += `### Required Skills\n`;
      explainData.required_skills.forEach((skill) => {
        md += `- \`${skill}\`\n`;
      });
      md += `\n`;
    }

    if (explainData?.jargon_explained && Object.keys(explainData.jargon_explained).length > 0) {
      md += `### Jargon Dictionary\n`;
      Object.entries(explainData.jargon_explained).forEach(([term, def]) => {
        md += `- **${term}**: ${def}\n`;
      });
      md += `\n`;
    }

    if (explainData?.relevant_files?.length > 0) {
      md += `### Relevant Files to Modify\n`;
      explainData.relevant_files.forEach((file) => {
        md += `- \`${file}\`\n`;
      });
      md += `\n`;
    }

    md += `---\n\n`;

    // 2. Implementation Plan
    md += `## 🗺️ 2. Implementation Plan\n\n`;
    if (planData) {
      md += `### Approach\n${planData.approach || 'N/A'}\n\n`;
      
      if (planData.steps?.length > 0) {
        md += `### Step-by-Step Execution\n`;
        planData.steps.forEach((step, idx) => {
          md += `${idx + 1}. ${step}\n`;
        });
        md += `\n`;
      }

      if (planData.testing_approach) {
        md += `### Testing Approach\n${planData.testing_approach}\n\n`;
      }

      if (planData.pr_checklist?.length > 0) {
        md += `### Pull Request Checklist\n`;
        planData.pr_checklist.forEach((item) => {
          md += `- [ ] ${item}\n`;
        });
        md += `\n`;
      }
    } else {
      md += `*Plan not generated yet. Visit Hacktoberfest Copilot to generate real-time AI implementation plan.*\n\n`;
    }

    md += `---\n\n`;

    // 3. Test Suggestions
    md += `## 🧪 3. Test Suite & Verification\n\n`;
    if (testsData) {
      md += `**Recommended Test Framework:** \`${testsData.test_framework || 'pytest / jest'}\`\n\n`;
      
      if (testsData.test_cases?.length > 0) {
        md += `### Test Cases\n`;
        testsData.test_cases.forEach((tc) => {
          md += `- 🧪 ${tc}\n`;
        });
        md += `\n`;
      }

      if (testsData.example_code) {
        md += `### Test Scaffolding Code\n\`\`\`\n${testsData.example_code}\n\`\`\`\n\n`;
      }
    } else {
      md += `*Test suite suggestions not generated yet.*\n\n`;
    }

    md += `---\n\n`;

    // 4. PR Description
    md += `## 📝 4. Ready-to-Use Pull Request Template\n\n`;
    if (prData) {
      md += `### PR Title\n\`${prData.title}\`\n\n`;
      md += `### PR Body\n\`\`\`markdown\n${prData.body}\n\`\`\`\n\n`;
    } else {
      md += `*PR description not generated yet.*\n\n`;
    }

    md += `---\n\n`;
    md += `*Happy contributing to Hacktoberfest 2026! Powered by Team GrandCoders.* 🚀\n`;

    return md;
  };

  const exportMarkdown = () => {
    const mdContent = generateMarkdownContent();
    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Hacktoberfest_Roadmap_Issue_${issueNumber}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    setIsOpen(false);
    if (onShowToast) onShowToast({ message: 'Roadmap downloaded as Markdown (.md)!', type: 'success' });
  };

  const printPdf = () => {
    setIsOpen(false);
    if (onShowToast) onShowToast({ message: 'Opening print dialog. Select "Save as PDF" to save.', type: 'info' });
    setTimeout(() => {
      window.print();
    }, 300);
  };

  const copyShareLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setIsOpen(false);
    if (onShowToast) onShowToast({ message: 'Direct roadmap link copied to clipboard!', type: 'success' });
  };

  return (
    <div className="export-dropdown-container" ref={dropdownRef}>
      <button 
        className="export-dropdown-btn"
        onClick={() => setIsOpen(!isOpen)}
        aria-expanded={isOpen}
        aria-haspopup="true"
        id="export-roadmap-btn"
      >
        <span>📥</span>
        <span>Export Roadmap</span>
        <span className="export-caret">{isOpen ? '▲' : '▼'}</span>
      </button>

      {isOpen && (
        <div className="export-dropdown-menu animate-fade-in">
          <button className="export-dropdown-item" onClick={exportMarkdown}>
            <span className="export-icon">📝</span>
            <div className="export-text">
              <strong>Export as Markdown (.md)</strong>
              <small>Download comprehensive offline guide</small>
            </div>
          </button>

          <button className="export-dropdown-item" onClick={printPdf}>
            <span className="export-icon">🖨️</span>
            <div className="export-text">
              <strong>Print / Save as PDF</strong>
              <small>Clean, printable report layout</small>
            </div>
          </button>

          <button className="export-dropdown-item" onClick={copyShareLink}>
            <span className="export-icon">🔗</span>
            <div className="export-text">
              <strong>Copy Shareable Link</strong>
              <small>Share with team members or mentors</small>
            </div>
          </button>
        </div>
      )}
    </div>
  );
}
